export const structs = `
Structs
  GUI
  context::ActiveAttribute
  context::ActiveTransformFeedback
  context::ActiveUniform
  context::Context
  context::DebugMessageLogEntry
  context::NativeBuffer
  context::NativeFence
  context::NativeFramebuffer
  context::NativeProgram
  context::NativeQuery
  context::NativeRenderbuffer
  context::NativeSampler
  context::NativeShader
  context::NativeTexture
  context::NativeTransformFeedback
  context::NativeUniformLocation
  context::NativeVertexArray
  context::ProgramBinary
  context::Version
  core::Context
  core::Program
  core::ScissorBox
  core::Viewport
  core::buffer::ElementBuffer
  core::buffer::InstanceBuffer
  core::buffer::UniformBuffer
  core::buffer::VertexBuffer
  core::prelude::AxisAlignedBoundingBox
  core::prelude::Deg
  core::prelude::Matrix2
  core::prelude::Matrix3
  core::prelude::Matrix4
  core::prelude::Point2
  core::prelude::Point3
  core::prelude::Quaternion
  core::prelude::Rad
  core::prelude::Srgba
  core::prelude::Vector2
  core::prelude::Vector3
  core::prelude::Vector4
  core::prelude::f16
  core::render_states::RenderStates
  core::render_states::WriteMask
  core::render_target::ClearState
  core::render_target::ColorTarget
  core::render_target::ColorTargetMultisample
  core::render_target::DepthTarget
  core::render_target::DepthTargetMultisample
  core::render_target::RenderTarget
  core::render_target::RenderTargetMultisample
  core::texture::CpuTexture
  core::texture::CpuTexture3D
  core::texture::CubeMapSideIterator
  core::texture::DepthTexture2D
  core::texture::DepthTexture2DArray
  core::texture::DepthTextureCubeMap
  core::texture::Mipmap
  core::texture::Texture2D
  core::texture::Texture2DArray
  core::texture::Texture3D
  core::texture::TextureCubeMap
  core::texture::f24
  renderer::Camera
  renderer::EffectMaterialId
  renderer::Frustum
  renderer::GeometryId
  renderer::IntersectionResult
  renderer::LightId
  renderer::TextGenerator
  renderer::TextLayoutOptions
  renderer::control::FirstPersonControl
  renderer::control::FlyControl
  renderer::control::FreeOrbitControl
  renderer::control::Modifiers
  renderer::control::OrbitControl
  renderer::control::PhysicalPoint
  renderer::effect::CopyEffect
  renderer::effect::FogEffect
  renderer::effect::FxaaEffect
  renderer::effect::ScreenEffect
  renderer::effect::WaterEffect
  renderer::geometry::BoundingBox
  renderer::geometry::Circle
  renderer::geometry::CpuMesh
  renderer::geometry::InstancedMesh
  renderer::geometry::Instances
  renderer::geometry::KeyFrameAnimation
  renderer::geometry::KeyFrames
  renderer::geometry::Line
  renderer::geometry::Mesh
  renderer::geometry::ParticleSystem
  renderer::geometry::Particles
  renderer::geometry::PointCloud
  renderer::geometry::Rectangle
  renderer::geometry::Sprites
  renderer::light::AmbientLight
  renderer::light::Attenuation
  renderer::light::DirectionalLight
  renderer::light::Environment
  renderer::light::PointLight
  renderer::light::SpotLight
  renderer::material::ColorMaterial
  renderer::material::CpuMaterial
  renderer::material::DeferredPhysicalMaterial
  renderer::material::DepthMaterial
  renderer::material::IntersectionMaterial
  renderer::material::IsosurfaceMaterial
  renderer::material::NormalMaterial
  renderer::material::ORMMaterial
  renderer::material::PhysicalMaterial
  renderer::material::PositionMaterial
  renderer::material::Texture2DRef
  renderer::material::UVMaterial
  renderer::object::Axes
  renderer::object::CpuModel
  renderer::object::CpuVoxelGrid
  renderer::object::Gm
  renderer::object::Imposters
  renderer::object::InstancedModel
  renderer::object::InstancedModelPart
  renderer::object::Model
  renderer::object::ModelPart
  renderer::object::Skybox
  renderer::object::Terrain
  renderer::object::VoxelGrid
  renderer::object::Water
  renderer::object::WaveParameters
  window::FrameInput
  window::FrameInputGenerator
  window::FrameOutput
  window::HeadlessContext
  window::SurfaceSettings
  window::Window
  window::WindowSettings
  window::WindowedContext

  `;
